Repository netlify/build-plugin-template, pull requests merged in 2020-10, with the labels that each got.

#9 refactor: use Denylist instead of Blacklist
  init/variables/name.js
Labels: type: chore

#10 chore: configure renovate
  renovate.json5
Labels: type: chore

#8 Changes src/main.js to index.js to match docs
  CONTRIBUTING.md
  README.md
  package.json
  src/index.js
  test/index.js
Labels: documentation, type: chore

#11 fix: broken link to tests
  README.md
Labels: type: bug

#12 fix: status badge link
  README.md
Labels: type: bug

#15 style: format readme
  README.md
Labels: type: bug

#13 chore: update deps
  package-lock.json
  package.json
Labels: type: chore
